### ISSUE TITLE
Screen: Add Job

### ISSUE THREAD

**Issue by wouerner** [SouJunior/vagas-frontend#11]

**Comment by allbertuu** [comment]
### Sub-tasks:

- [ ] Decidir qual será a forma de estilização das Pages
  > 

#### Etapas no código 

- [ ] Header
- [ ] Main
- [ ] Footer

**Comment by allbertuu** [comment]
> Aguardando alinhamento com o UI/UX, pois esta tela está com elementos quebrados no layout.

**Comment by allbertuu** [comment]
Esperando resolução/retorno das observações feitas por @allbertuu (eu mesmo) desta tela no protótipo Figma. @Rica-Jesus

**Comment by allbertuu** [comment]
Após reunião com membros da equipe de UI/UX, essa task está parada por conta de várias inconsistências no prótotipo que necessitam revisão da equipe de UI/UX.

**Comment by Rica-Jesus** [comment]
@JeanVictorferreira @SouJunior/ux temos algum retorno sobre este block?
