### ISSUE TITLE
Criar Conta Candidato - Criar formulário

### ISSUE THREAD

**Issue by igords-goncalves** [SouJunior/vagas-frontend#111]
US referente: https://github.com/orgs/SouJunior/projects/3/views/1?pane=issue&itemId=22945724
_____
Figma referente: https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX---(-Update-19%2F10%2F2022-)?node-id=89%3A3&t=wn9fqUzX5pFkKGTE-0

## Descrição

- [x] Criar Formulário
- [x] Validar Formulário

## Recursos

API backend: https://dev-backend-vagas.up.railway.app/api/#/

![Image](https://user-images.githubusercontent.com/79734585/225480854-2346cce9-8660-4f8d-b757-14b999269ca8.png)

**Comment by igords-goncalves** [comment]
Aguardaremos até que o time de @SouJunior/ux crie o formulário de cadastro do candidato.

**Comment by Jacqueline2021** [comment]
@igords-goncalves A US referente está incorreta. O link correto é este: https://github.com/orgs/SouJunior/projects/3/views/1?pane=issue&itemId=22945724

**Comment by igords-goncalves** [comment]
A mesma questão sobre o campo CPF se repete aqui.

Saiba mais em https://github.com/SouJunior/vagas-frontend/issues/112#issuecomment-1471133786

**Comment by igords-goncalves** [comment]
## Bug de validação cadastro de usuários.

Estou enfrentando um bug de validação relacionado ao form de cadastro de usuários e form de login.

No arquivo **validations** onde acontecem todas as validações de `inputs`, quando descomento todo o código que faz a validação do form de cadastro como na ultima imagem, a submissão do form de login seguindo o padrão do React Hook Form como na imagem abaixo, fica impossibilitada. O botão não envia a submissão nenhuma e ao que parece também se torna não clicavel.

![image](https://user-images.githubusercontent.com/79734585/227066560-85d3289c-9b01-4554-8f14-fc00d90e48fc.png)

 A situação da possibilidade de click só se resolve quando a submissão acontece dentro do botão com da forma tradicional com o método `onChange( )` do button, porém um novo bug surge, a função que faz de fato o login como na imagem abaixo, só realiza de o login quando o método `preventDefault( )` é inserido dentro da função e, primeira posição ou no campo de submissão do React Hook Form onde aconteceria a chamada da função de login seguindo a forma do React Hook Form como citei acima.

![image](https://user-images.githubusercontent.com/79734585/227066839-ccd2e4d8-219c-4c6f-82c5-2889e4073d23.png)

O que descobri foi que o erro que causa esses problemas no form de login estão na validação do form de cadastro, após comentar os códigos como na imagem abaixo tudo funciona como deveria, sem o `preventDefault( )` e com a submissão feita no campo React Hook Form.

![image](https://user-images.githubusercontent.com/79734585/227067341-91f9d9b9-aa03-435a-ae9e-2a80778e9145.png)

> É importante ressaltar que o erro acontece tanto nos forms de candidato e empresa pois o código é praticamente o mesmo, um possível erro quanto a submissão do cadastro dos usuários também pode acontecer, só não foi feito o teste ainda pois estamos com problemas no servidor.

**Comment by Andrezapsilva** [comment]
Boa noite, 

Alguém sabe me informar se foi feito a criação do formulário ?
Dia 13 de Março @igords-goncalves informou que estava aguardando.

Abre uma pagina Not Found - Back-end da API: https://dev-backend-vagas.up.railway.app/api/#/

![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/28757b85-3ac2-4296-9389-1fa85cfb6e44)

**Comment by denyscarvalho** [comment]
@SouJunior/ux @LuandaClara  Podem verificar a respeito dessa criação do formulário?

**Comment by denyscarvalho** [comment]
@Andrezapsilva Segue endereço da API https://vagas-backend.soujunior.tech/API/

**Comment by Andrezapsilva** [comment]
Criar Formulário
 Validar Formulário

**Comment by Andrezapsilva** [comment]
CT001: Criar Formulário



![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/24ff3380-36b2-4632-b49a-42c8a23611b5)



![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/237d5d59-b863-480f-ba85-835ccc842a14)

STATUS : PASSOU

**Comment by Andrezapsilva** [comment]
CT002.01: Validar Formulário - Campo Foto

**Comment by Andrezapsilva** [comment]
CT002.02: Validar Formulário - Nome completo

**Comment by Andrezapsilva** [comment]
CT002.03: Validar Formulário - E-mail

**Comment by Andrezapsilva** [comment]
CT002.04: Validar Formulário - Cidade

**Comment by Andrezapsilva** [comment]
CT002.05: Validar Formulário - UF

**Comment by Andrezapsilva** [comment]
CT002.06: Validar Formulário - Telefone 1

**Comment by Andrezapsilva** [comment]
CT002.07: Validar Formulário - Telefone 2

**Comment by Andrezapsilva** [comment]
CT002.08: Validar Formulário - Currículo 1

**Comment by Andrezapsilva** [comment]
CT002.09: Validar Formulário - Currículo 2

**Comment by Andrezapsilva** [comment]
CT002.10: Validar Formulário - Atualizar

**Comment by Andrezapsilva** [comment]
Reteste de Bugs em andamento:

 CT002.01: Validar Formulário - Campo Foto
 CT002.02: Validar Formulário - Nome completo
 CT002.10.01: Validar Formulário - Atualizar Sem Campos Obrigatórios Preenchidos
 CT002.10.02: Validar Formulário - Atualizar Com Campos Obrigatórios Preenchidos

 CT002.06: Validar Formulário - Telefone 1
Obs.: O campo não assume o formato (00) 00000-0000, contido no campo inicialmente.
 CT002.07: Validar Formulário - Telefone 2
Obs.: O campo não assume o formato (00) 00000-0000, contido no campo inicialmente. 

 CT002.03: Validar Formulário - E-mail
Conforme conversado com a @isabelahyeda, na historia #221, há a regra de negocio onde o e-mail não será alterado a principio.

**Comment by isabelahyeda** [comment]
@Andrezapsilva PR aprovado e pronto para reteste.

**Comment by Andrezapsilva** [comment]
Reteste de Bugs:

CT002.01: Validar Formulário - Campo Foto
CT002.02: Validar Formulário - Nome completo
CT002.10.01: Validar Formulário - Atualizar Sem Campos Obrigatórios Preenchidos 
CT002.10.02: Validar Formulário - Atualizar Com Campos Obrigatórios Preenchidos
CT002.06: Validar Formulário - Telefone 1

CT002.07: Validar Formulário - Telefone 2

CT002.03: Validar Formulário - E-mail Conforme conversado com a , na história https://github.com/SouJunior/products/issues/221, há a regra de negócio onde o e-mail
estará desabilitado, sem a possibilidade de edição.

STATUS :  PASSOU



![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/fc22704f-9815-484a-817a-70a7bae992a8)
