### ISSUE TITLE
Criar conta candidato - Submeter formulário

### ISSUE THREAD

**Issue by igords-goncalves** [SouJunior/vagas-frontend#112]
US referente: https://github.com/orgs/SouJunior/projects/3/views/1?pane=issue&itemId=22945724
____
Figma referente: https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX---(-Update-19%2F10%2F2022-)?node-id=89%3A3&t=wn9fqUzX5pFkKGTE-0

## Descrição

Trata-se da submissão do formulário de cadastro do usuário.

- [x] Criação de submissão do usuário criado
- [x] Integração com API backend correta
- [x] Redirecionamento para página autorizada
- [x] Utilizar página em branco simulando página home para acesso não autorizado
- [x] Utilizar página em branco simulando página de acesso autorizado

## Recursos

API backend: https://dev-backend-vagas.up.railway.app/api/#/

**Comment by Jacqueline2021** [comment]
@igords-goncalves A US referente está incorreta. O link correto é este: https://github.com/orgs/SouJunior/projects/3/views/1?pane=issue&itemId=22945724

**Comment by igords-goncalves** [comment]
Boa noite @Jacqueline2021  @brunodev21 no design atual e nos critérios da US referente a essa task #112 não é mais necessário que o usuário do tipo candidato insira o CPF, porém como regra estabelecida no back-end o usuário precisa inserir seu CPF para conseguir criar uma conta como conta no teste de criação de usuário feito abaixo.



![Image](https://user-images.githubusercontent.com/79734585/225484951-e7fc15b4-337c-4e92-97e8-e88e762737e3.png)

### Design Atual sem o CPF

![Image](https://user-images.githubusercontent.com/79734585/225485062-4d20d58b-83b9-43a2-85aa-f83e6e45c616.png)

**Comment by wandersonDeve** [comment]
essa demanda o pessoal do backend ainda não pedou esta no backlog da sprint

![image](https://user-images.githubusercontent.com/81826043/225610670-403e72b7-aa68-4830-ae9c-35da5a5d4cf9.png)

**Comment by igords-goncalves** [comment]
Beleza então será atualizada essa questão do CPF, show de bola, obrigado! A propósito que trabalho profissional vcs fizeram com a API ficou impressionante.

**Comment by wandersonDeve** [comment]
O pessoal manda bem, porem estão sem tempo devido a faculdade.

**Comment by igords-goncalves** [comment]
Atualização da API https://linkedin-backend-production-4a92.up.railway.app/

**Comment by igords-goncalves** [comment]
A questão da obrigatoriedade do CPF ainda consta nos testes que fiz coma  nova API, estou em contato com o Pedro responsável pelo back do time akamaru.

![Image](https://user-images.githubusercontent.com/79734585/227647483-0403586d-14a1-482c-bc51-8076e2940005.png)

**Comment by wandersonDeve** [comment]
Existe dois comentarios na PR que precisa ser resolvido antes de eu aprovar ele.

**Comment by igords-goncalves** [comment]
Atualização da API   https://vagas-backend.soujunior.tech/

Desconsiderar a versão acima.

**Comment by Andrezapsilva** [comment]
Boa noite,

Alguém sabe me informar se foi feito a submissão do formulário ?
Dia 16 de Março @wandersonDeve informou que backend ainda não havia pego essa task, ela está no backlog da sprintestava aguardando.

Dia 31 de Março @igords-goncalves colocou Atualização da API https://vagas-backend.soujunior.tech/ porem abre apenas essa pagina:



![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/3a854439-bdbd-49d4-be5f-c6f9694700c4)

**Comment by Andrezapsilva** [comment]
Trata-se da submissão do formulário de cadastro do usuário.

 Criação de submissão do usuário criado
 Integração com API backend correta
 Redirecionamento para página autorizada
 Utilizar página em branco simulando página home para acesso não autorizado
 Utilizar página em branco simulando página de acesso autorizado
