### ISSUE TITLE
[Empresa / Cadidato] Acessar portal e redirecionar

### ISSUE THREAD

**Issue by igords-goncalves** [SouJunior/vagas-frontend#113]
US referente: https://github.com/orgs/SouJunior/projects/3/views/1?pane=issue&itemId=11661893
____
Figma referente: https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX---(-Update-19%2F10%2F2022-)?node-id=89%3A3&t=wn9fqUzX5pFkKGTE-0

## Descrição

Integrar sistema e realizar autenticação com API correta.

- [x] Criar sistema de seleção de tipos de usuários renderizando um formulário para cada tipo de usuário.
- [x] ~Habilitar/Desabilitar botão do usuário que for selecionado para login~
- [x] Realizar as requisições para a API correta.
- [x] Redirecionar o usuário de acordo com seu tipo
- [x] Verificar sistema de autenticação entre empresa cadastrada e login no sistema.
- [x] Criar página de redirecionamento para tela de login, ou seja, pagina Home
- [x] Criar página de redirecionamento após login, ou seja, Feed de Vagas
- [x]  Criar conta de empresa
- [x] Criar persistência de login

## Recursos

API backend: https://dev-backend-vagas.up.railway.app/api/#/

**Comment by igords-goncalves** [comment]
Por definição e regras do lado do servidor não é possível realizar o login sem definir o tipo de usuário antes. 


![Image](https://user-images.githubusercontent.com/79734585/225305769-9afde025-f961-4001-8b79-0d1e2109751e.png)

**Comment by igords-goncalves** [comment]
Teste e tratativa de erro referente ao usuário tentando realizar login com outro tipo de usuário, por exemplo usuário do tipo candidato tentando logar como empresa, o erro exibido será de **E-mail ou senha não conferem como consta na imagem abaixo.**

![image](https://user-images.githubusercontent.com/79734585/225386742-71b5aebe-bc0d-4edf-acaa-6fd117b40ffe.png)

**Comment by igords-goncalves** [comment]
@LuandaClara @SouJunior/ux @SouJunior/apm @Jacqueline2021

1. Ali na tela de Login onde vc pode observar a palavra empresa quando o tipo de usuário selecionado é empresa , antes era escrito Entrar como no figma, troquei para o nome do tipo de usuário que fara login por acreditar que fica ainda mais intuitivo saber qual usuário está fazendo login e também por conta da estratégia usada para renderizar os formulários de acordo com o tipo de usuário, no caso empresa ou candidato.

2. Outra alteração que gostaria de realizar é apagar o botão do formulário que não estiver selecionado se for logar ou cadastrar uma empresa, o bot;ao candidato ficará apagado e vice e versa.

**Gostaria de saber o que vcs pensam sobre essas alterações e se posso prosseguir.**

### Antes
![image](https://user-images.githubusercontent.com/79734585/225417756-babfff15-b9dc-403b-b717-aca7fb385a19.png)

### Depois
Observe que não é mais entra, mas sim o tipo de usuário a fazer login.

https://user-images.githubusercontent.com/79734585/225418285-bd79adeb-eed9-4d4e-8e19-7a5639692926.mp4

**Comment by igords-goncalves** [comment]
Requisições de login do tipo Company já estão funcionando.

![Image](https://user-images.githubusercontent.com/79734585/226221168-6be9a1e8-c7f9-4b43-99ae-43e1c44eddb3.png)

**Comment by igords-goncalves** [comment]
Boa noite @brunodev21 e @SouJunior/backend estou tentando realizar um teste de criação da empresa atrelado também a task https://github.com/SouJunior/vagas-backend/issues/81, mas sempre retornando o mesmo erro referente ao CNPJ  como segue na imagem. Achei que poderia estar realizando o teste de forma errada, por isso peço uma ajuda por gentileza, para verificarmos se realmente existe um problema.

![image](https://user-images.githubusercontent.com/79734585/226468113-b35ddbb8-a89f-434d-965d-090f9437c900.png)

**Comment by igords-goncalves** [comment]
Atualização da API https://linkedin-backend-production-4a92.up.railway.app/

**Comment by igords-goncalves** [comment]
Atualização da API   https://vagas-backend.soujunior.tech/

Desconsiderar a versão acima.

**Comment by igords-goncalves** [comment]
Prezados em conversas com o pessoal de QA percebemos que algumas obrigatoriedades que existem no back-end e não existem nas US estão impedindo o front-end quanto ao avanço do cadastro do usuário tipo empresa, e também estamos tendo impedimentos quando ao uso da API de deploy citada acima qualquer ação ou requisição realizadas resulta em um erro.

**Comment by wandersonDeve** [comment]
Irei ver o deploy mencionado

**Comment by igords-goncalves** [comment]
> @igords-goncalves  Verifica ai como ta a API agora eu atualizei ela com o deploy que estava antes. 
> Agora é pra ele estar deacorodo com a US
> 
> Swagger.: https://vagas-backend.soujunior.tech/api/

Perfeito, mais tarde ao sair do trabalho realizarei todos os teste, e mais uma vez agradeço pela resposta sempre rápida e pelo excelente trabalho que o time vem fazendo.

**Comment by igords-goncalves** [comment]
> @igords-goncalves quais são essas obrigatoriedades que estão divergindo? 
Endereço 
LinkedIn
Descrição

Sem esses dados o cadastro não pode ser realizado! Mas como menciona o deploy foi corrigido realizarei os testes necessários.

**Comment by Jacqueline2021** [comment]
> > @igords-goncalves quais são essas obrigatoriedades que estão divergindo? 
> Endereço 
> LinkedIn
> Descrição
> 
> Sem esses dados o cadastro não pode ser realizado! Mas como mencionado o deploy foi corrigido, logo realizarei os testes necessários. 

Ah ok! Qualquer coisa é só chamar. Obrigada timeeee!

**Comment by igords-goncalves** [comment]
Toda parte de integração back e front finalizada, usuários sendo criados com sucesso!


![Image](https://user-images.githubusercontent.com/79734585/229953052-4572ccc8-0df8-4ee7-b208-886f6eff0a7f.png)

![Image](https://user-images.githubusercontent.com/79734585/229953059-1942b7df-a947-42f6-a445-668d2575d278.png)

**Comment by igords-goncalves** [comment]
Retornos com status de sucesso.

![Image](https://user-images.githubusercontent.com/79734585/229953186-0a37cd8c-63ba-40c0-b573-3f1f996fbfd9.png)

**Comment by Jacqueline2021** [comment]
Sensacional! Que notícia boa!

**Comment by Andrezapsilva** [comment]
Bugs:

- [ ] CT001: Teste 1 Empresa - Login no portal da a seguinte mensagem: desculpe, algo inesperado aconteceu
- [ ] CT002: Teste 2 Candidato - Login no portal da a seguinte mensagem: desculpe, algo inesperado aconteceu

**Comment by Andrezapsilva** [comment]
Evidencias:

CT001 Teste 1 Empresa - Login no portal



![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/24ed24f5-1d1e-4c87-80d8-3a405ddd48d0)



CT002 Teste 2 Candidato - Login no portal 



![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/443369fc-1b22-48a1-851f-6325950f3665)

**Comment by Andrezapsilva** [comment]
Criar página de redirecionamento para tela de login, ou seja, pagina Home
 Criar página de redirecionamento após login, ou seja, Feed de Vagas
 Criar conta de empresa
 Criar persistência de login

**Comment by Andrezapsilva** [comment]
A Task pode seguir o fluxo @vivianaschmidt t e @denyscarvalho .
