### ISSUE TITLE
[Candidato] - Acessar portal e redirecionar

### ISSUE THREAD

**Issue by igords-goncalves** [SouJunior/vagas-frontend#114]
US referente: https://github.com/orgs/SouJunior/projects/3/views/1?pane=issue&itemId=22945724
Figma referente: https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX---(-Update-19%2F10%2F2022-)?node-id=89%3A3&t=wn9fqUzX5pFkKGTE-0

## Descrição

Integrar sistema e realizar autenticação com API correta.

- [x] Realizar as requisições para a API correta.
- [x] Redirecionar o usuário de acordo com seu tipo
- [x] Criar página de redirecionamento após login

## Recursos

API backend: https://dev-backend-vagas.up.railway.app/api/#/

**Comment by Jacqueline2021** [comment]
@igords-goncalves A US referente está incorreta. O link correto é este: https://github.com/orgs/SouJunior/projects/3/views/1?pane=issue&itemId=22945724

**Comment by igords-goncalves** [comment]
É que foi um modelo reaproveitado, esqueci de trocar o link, obrigado!

**Comment by igords-goncalves** [comment]
Atualização da API https://linkedin-backend-production-4a92.up.railway.app/

**Comment by igords-goncalves** [comment]
Atualização da API   https://vagas-backend.soujunior.tech/

Desconsiderar a versão acima.

**Comment by JanainaRodrigues07** [comment]
Testes Feitos

Testes de Funcionalidade: 
- ID: 0001 - CT001: Acessar Portal como Candidato - C01: Fazer login com dados válidos
- ID: 0001 - CT001: Acessar Portal como Candidato - C02: Verificar redirecionamento

Teste de API: 
- ID: 0002 - CT002: Requisição para a API correta - C01: Fazer login com dados válidos 

CONCLUSÃO: Todos os testes passarm

@Jacqueline2021 @denyscarvalho

**Comment by JanainaRodrigues07** [comment]
Testes de Funcionalidade: [Candidato] Acessar Portal 

Feito em https://deploy-preview-226--vagas-front-end.netlify.app/

**ID: 0001**
CT001: Acessar Portal como Candidato 

C01: Fazer login com dados válidos

Dados de entrada: 
  email: johnsnow@outlook.com
  senha: Abcd@1234

Saída: Login efetuado com sucesso

STATUS: PASSOU

Evidência:


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/32a1f86d-400b-4d14-9bfa-876a4d74e76e)



C02: Verificar redirecionamento

Dados de entrada: 
  email: johnsnow@outlook.com
  senha: Abcd@1234

STATUS: PASSOU

Evidência:


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/7b011589-b89b-4493-a1e6-d2f4b75af28a)

**Comment by JanainaRodrigues07** [comment]
**ID: 0002**
Feito em API: https://vagas-backend.soujunior.tech/api/#/  (Atualização de API)
Rota para login: /auth/login

CT002: Requisição para a API correta 
C01: Fazer login com dados válidos 

Dados de entrada:
{
  "email": "johnsnow@outlook.com",
  "password": "Abcd@1234",
  "type": "USER"
}

Resultado esperado: 
200 OK

Resultado obtido:
200 OK

STATUS: PASSOU

Evidência:


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/4784cff6-b4a8-48b4-9131-9aa746bb0799)

**Comment by JanainaRodrigues07** [comment]
**ID: 0003**

CT003: Testar design responsivo de página de redirecionamento

C01: Teste de tela de smart phone na posição vertical

Descrição: teste feito em telas na posição vertical com tamanhos a partir de 357x668 e maiores

STATUS: PASSOU

Evidência:


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/f5d9a310-00ca-4ff9-8830-bdccbc146eec)

_______________________________________________________________________________________________________________________________________

C02: Teste de tela de smart phone na posição horizontal

Descrição: teste feito em telas na posição vertical com tamanhos a partir de 668x357 e maiores

STATUS: PASSOU

Evidência:


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/d048647f-a22e-4fe1-8153-c61687d803cd)

_______________________________________________________________________________________________________________________________________

C03: Teste de tela de tablet na posição vertical

Descrição: teste feito em telas na posição vertical com tamanhos de 768x1024

STATUS: PASSOU

Evidência:

![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/f4c92c0d-89cf-4ef5-a85b-dbcc8654190d)

_______________________________________________________________________________________________________________________________________

C04: Teste de tela de tablet na posição horizontal

Descrição: teste feito em telas na posição vertical com tamanhos de 1024x768

STATUS: PASSOU

Evidência:



![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/565720b9-8684-4d36-9f25-54dfa4a2068a)
