### ISSUE TITLE
[Empresa / Candidato] Esqueci a senha - Form de Confirmação

### ISSUE THREAD

**Issue by isabelahyeda** [SouJunior/vagas-frontend#122]
Links das US: 
https://github.com/SouJunior/products/issues/16 (empresa)
https://github.com/SouJunior/products/issues/33 (candidato)

Link do Figma - https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX---(-Update-19%2F10%2F2022-)?node-id=2541%3A2320&t=tcKYGwC4zHXnZa3J-0

**Descrição:**

- [x] Criar formulário
- [x] Validar formulário

**Comment by JanainaRodrigues07** [comment]
Testes Exploratórios

- TE01: [Empresa/Candidato] Ao clicar no campo “Esqueci a senha” sou direcionada a uma outra página para confirmar meu e-mail.
- TE02: [Empresa/Candidato] Confirmar e-mail com e-mail válido
- TE03: [Empresa/Candidato] Confirmar e-mail com e-mail inválido

Testes de API

- TA01: [Empresa/Candidato] Confirmar e-mail com e-mail válido
- TA02: [Empresa/Candidato] Confirmar e-mail com e-mail inválido

CONCLUSÃO: Todos os testes passaram

@denyscarvalho @LuizGuilhermeNeves

**Comment by JanainaRodrigues07** [comment]
Testes Exploratórios

TE01: [Empresa/Candidato] Ao clicar no campo “Esqueci a senha” sou direcionada a uma outra página para confirmar meu e-mail.

STATUS: PASSOU

Evidência:

[Conta Empresa]


https://github.com/SouJunior/vagas-frontend/assets/110006150/fa08fe79-c034-4805-9587-6844157296b9


[Conta Candidato]



https://github.com/SouJunior/vagas-frontend/assets/110006150/3a131216-3a5c-4a71-a195-9a02e033e40d


---------------------------------------------------------------------------------------------------------------------------------
TE02: [Empresa/Candidato] Confirmar e-mail com e-mail válido

STATUS: PASSOU

Evidência:

[Conta Empresa]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/6d21e277-7823-4d7a-b03b-7feb7b902496)


[Conta Candidato]



![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/12d3acbc-4a39-4a31-9a30-dd2b47f1a1f3)

---------------------------------------------------------------------------------------------------------------------------------
TE03: [Empresa/Candidato] Confirmar e-mail com e-mail inválido

STATUS: PASSOU

Evidências:

[Conta Empresa]



![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/382dbd12-b634-42af-bf0e-1bde592509e0)
![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/c0482b00-3311-4ec7-a101-f6f823f6109f)




[Conta Candidato]



![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/6c03fda0-e3d4-41bd-82dd-f280b7b71f61)
![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/961417a6-1751-469c-8634-d49023679187)

**Comment by JanainaRodrigues07** [comment]
Testes de API

TA01: [Empresa/Candidato] Confirmar e-mail com e-mail válido

Dados de Entrada para Conta Empresa:
{
"email": "bomed96225@poverts.com"
}

Dados de Entrada para Conta Candidato:
{
"email": "colegex866@poverts.com"
}

Resultado esperado:
200 OK
Mensagem: "Caso esse e-mail esteja cadastrado no sistema, será encaminhado para ele uma mensagem de orientação sobre os próximos passos para a redefinição da senha."

Resultado obtido:
200 OK
Mensagem: "Caso esse e-mail esteja cadastrado no sistema, será encaminhado para ele uma mensagem de orientação sobre os próximos passos para a redefinição da senha."

STATUS: PASSOU

Evidência:

[Conta Empresa]



![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/b8287e4b-22d4-470e-89ff-74999b1e8c35)




[Conta Candidato]



![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/1d4dc7cb-11f6-45c3-951f-3fadfee4f851)

------------------------------------------------------------------------------------------------------------------------------------
TA02: [Empresa/Candidato] Confirmar e-mail com e-mail inválido

Dados de Entrada para Conta Empresa:
{
"email": "empresaone@companybr"
}

Dados de Entrada para Conta Candidato:
{
"email": "candidato1@usercom"
}

Resultado esperado:
400 Bad Request

Resultado obtido:
400 Bad Request


STATUS: PASSOU

Evidência:

[Conta Empresa]



![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/9bf5d76e-77b4-43be-83a1-73c795026a52)




[Conta Candidato]



![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/38b6ef39-4c36-4cd2-9dba-16b92a2c7fec)
