### ISSUE TITLE
[ Empresa / Candidato ] Esqueci a senha - Template de email redefinição e recuperação

### ISSUE THREAD

**Issue by igords-goncalves** [SouJunior/vagas-frontend#132]
figma: https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX?node-id=2541-2319&t=eGwzEk3iSUaQNR0z-0

**Comment by igords-goncalves** [comment]
Obs. ficou definido com o @SouJunior/backend que criaremos um arquivo html com css interno para dar estilo ao devido template.

**Comment by wandersonDeve** [comment]
Obs.: fazer o templante apontado para o outlook, pois algumas configurações não funcionam na microsoft

**Comment by Andrezapsilva** [comment]
Boa Noite, 
Segundo Igor em 10/04 ficou definido com o backend que seria criado um arquivo html com css interno para dar estilo ao devido template.
Fiz o teste e não há pagina de recuperação de senha, após usuário "Empresa / Candidato clicar no botão Recuperar minha senha."


https://github.com/SouJunior/vagas-frontend/assets/140206807/468f23a9-b39f-4de9-9ff5-2ad914100aba

Alguém tem mais informações sobre @denyscarvalho @Leodias2204, aguardo retorno.

**Comment by Andrezapsilva** [comment]
Evidencia:

https://github.com/SouJunior/vagas-frontend/assets/140206807/468f23a9-b39f-4de9-9ff5-2ad914100aba

**Comment by Andrezapsilva** [comment]
Evidencia Candidato:

**Comment by denyscarvalho** [comment]
@Wanderson o pessoal do Front-End já tinha levantado essa dúvida se seria o Backend ou Front-end responsável pela criação desse Template. Sabe nos informar o que ficou definido?

**Comment by isabelahyeda** [comment]
@Andrezapsilva e @JanainaRodrigues07 templates ajustados e repassados para o back-end

**Comment by denyscarvalho** [comment]
@PatrickOtero @wandersonDeve @SouJunior/backend Pessoal, poderiam por gentileza analisar se há alguma pendência em relação ao backend nessa task em fase de teste? O pessoal de QA aguarda sinalização para continuar os testes.
Agradeço!!!

**Comment by isabelahyeda** [comment]
@Andrezapsilva @denyscarvalho Segundo atualizações do Patrick no Discord, tudo certo.

**Comment by PatrickOtero** [comment]
Nesse caso, resta saber se a referida página já foi construída pelo front-end. Se caso foi, tudo que o back-end precisa é da URL da mesma.

**Comment by Andrezapsilva** [comment]
Evidências de Testes:


[ Candidato ] Esqueci a senha - Template de email redefinição e recuperação:
![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/2a477732-6674-405a-a550-2ed3ee66e620)
![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/5f1f13b9-6a43-4cb6-8f54-db6b2291a73d)

Status: PASSOU


[ Empresa ] Esqueci a senha - Template de email redefinição e recuperação:
![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/6bc8eb50-95a7-4785-9459-0e31c459bd4e)
![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/a6231bca-650e-49c3-a0b2-bbff99b6f6dd)


Status: PASSOU

**Comment by Andrezapsilva** [comment]
Task 132 passou nos testes.
@denyscarvalho e @vivianaschmidt @vivianaschmidt
