### ISSUE TITLE
[ Empresa/ Candidato ] - Criar conta - Template de email de validação

### ISSUE THREAD

**Issue by igords-goncalves** [SouJunior/vagas-frontend#133]
US referente:
- https://github.com/SouJunior/products/issues/110
- https://github.com/SouJunior/products/issues/2

Figma referente: [Figma](https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX---(-Update-19%2F10%2F2022-)?node-id=89%3A3&t=wn9fqUzX5pFkKGTE-0)

## Descrição
 

- [x] Criar design num arquivo HTML separado.
- [x] Utilizar CSS interno.
- [x] Armazenar arquivo em google drive
- [x] Enviar arquivo para o backend

## Recursos

API backend: https://vagas-backend.soujunior.tech/

______

![Image](https://user-images.githubusercontent.com/79734585/231598831-934694d7-9486-49b8-a569-9901584fdf3a.png)

**Comment by igords-goncalves** [comment]
Obs. ficou definido com o @SouJunior/backend que criaremos um arquivo html com css interno para dar estilo ao devido template.

**Comment by igords-goncalves** [comment]
Finalizado sem Pull Request, arquivos enviados ao @SouJunior/backend 



![Image](https://user-images.githubusercontent.com/79734585/233446668-d441ebde-3569-4e93-aa3d-de7afed3a5b1.png)
![Image](https://user-images.githubusercontent.com/79734585/233446669-d123583e-91f3-4dfa-aca8-8c0dd0aec55a.png)

**Comment by Andrezapsilva** [comment]
Bugs:

**Comment by Andrezapsilva** [comment]
Exemplo de Teste

CT001: Tamplate de e-mail - g-mail


![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/90af09dd-5ede-4c37-8e75-024c5bb62ce0)


![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/901d27be-ad03-4ece-83bc-57e881d0a9ef)


![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/4d4750d4-d809-48f8-9dbc-be1df6395ae3)



![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/08c50d4b-19c7-4d0e-845e-561082359239)


Obs: A formatação do Tamplate no g-mail não esta correta. Fiz o teste em algum g-mails diferetes com a formatação do e-mail diferente e em todas esta aparecendo da mesma forma.

**Comment by Andrezapsilva** [comment]
CT002: Tamplate de e-mail - mohmal



![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/99811f42-0975-44a0-9e19-5d22920f605c)

STATUS: PASSOU

**Comment by Andrezapsilva** [comment]
CT002: Tamplate de e-mail -  tempmailfree



![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/30e83bd4-6f25-44a8-b0ba-a7817ed81368)


STATUS: PASSOU

**Comment by Andrezapsilva** [comment]
CT004: Tamplate de e-mail - uorak



![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/dc3c85b8-f187-4fd0-a639-e7885f6a9dae)



STATUS: PASSOU

**Comment by Andrezapsilva** [comment]
![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/75d0eef6-fa19-44ba-80aa-409b26aa0637)

**Comment by Andrezapsilva** [comment]
Exemplo de Teste Candidato

CT001: Tamplate de e-mail - g-mail



![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/a934308b-cc07-4ca9-a950-80979f5354f3)



STATUS: PASSOU

**Comment by Andrezapsilva** [comment]
CT002: Tamplate de e-mail - mohmal



![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/ff460eec-e2ea-4513-9fcf-19a816d03dda)



STATUS: PASSOU

**Comment by Andrezapsilva** [comment]
CT003: Tamplate de e-mail - tempmailfree



![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/f3a27504-fe89-4c91-aec3-564a803b2fa2)



STATUS: PASSOU

**Comment by Andrezapsilva** [comment]
CT004: Tamplate de e-mail - uorak



![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/bd591aeb-85f5-4b30-9e46-67e8f8090b8f)



STATUS: PASSOU

**Comment by Andrezapsilva** [comment]
CT005: Tamplate de e-mail - g-mail mobile


![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/699df155-6f04-4620-afb9-025dd31ad6d1)

STATUS: PASSOU

**Comment by isabelahyeda** [comment]
@Andrezapsilva fiz ajustes nos templates e já encaminhei para o back-end.

Bugs:

Confirmação de Cadastro de Empresa:

 CT001: Formatação do gmail website não esta correta.
 CT005: Formatação do gmail mobile não esta correto

Confirmação de Cadastro de Candidato:
Todos os Testes Passaram. OBS: no template de cadastro candidato a única alteração que fiz foi no src das imagens que representam os ícones das redes sociais, para não ficar com fundo escuro.

**Comment by Andrezapsilva** [comment]
RETESTE:

 CT001: Formatação do gmail website não esta correta.



Obs: A formatação do Tamplate no g-mail não esta correta. Fiz o teste em algum g-mails diferetes com a formatação do e-mail diferente e em todas esta aparecendo da mesma forma.

STATUS: FALHOU

**Comment by isabelahyeda** [comment]
@Andrezapsilva Só para registrar na atividade. Houve um problema com o deploy e por isso o template testado segue sendo o mesmo, sem as atualizações.

Assim que resolvido atualizo aqui

**Comment by isabelahyeda** [comment]
@Andrezapsilva atualizações feitas. O componente para confirmar e-mail ainda não existe.

**Comment by Andrezapsilva** [comment]
Reteste de Bugs:

Evidencias:

Confirmação de Cadastro de Empresa

 CT001: Formatação do gmail website.


![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/31bde1a0-5a5e-4aa4-8863-9c6f87fa28b8)

Obs: A formatação do Tamplate no g-mail está correta. Fiz o teste em algum g-mails diferetes com a formatação do e-mail diferente e em todas esta correta.

STATUS: PASSOU

 CT005: Formatação do gmail mobile.


![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/049718e8-4b1f-4a81-96c2-e7613d2b30e1)

Obs: A formatação do Tamplate no g-mail está correta. Fiz o teste em algum g-mails diferetes com a formatação do e-mail diferente e em todas esta correta.

STATUS: PASSOU

Confirmação de Cadastro de Empresa e Confirmação de Cadastro de Candidato:
Todos os Testes Passaram.

A Task pode seguir o fluxo @vivianaschmidt e @denyscarvalho.

**Comment by Andrezapsilva** [comment]
Todos os Testes Passaram.
Confirmação do cadastro após clicar em "Confirmar meu e-mail"

![Image](https://github.com/SouJunior/vagas-frontend/assets/140206807/8a8b163f-ad09-401f-9e00-386ece738904)

A Task pode seguir o fluxo @vivianaschmidt e @denyscarvalho.
