### ISSUE TITLE
[Cadidato / Feed de vagas] - Detalhes da vaga

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#139]
US Referente: https://github.com/SouJunior/products/issues/37

## SubTasks

- [x] Estilizar o componente
- [x] Implementar Skeleton Loading
- [x] Mudar url para ser possivel compatilhar a vaga

**Comment by FernandoMiguelS** [comment]
Boa noite, ficou um pouco abstrato essas subtarefas, poderia explicar?

**Comment by caiquefonseca** [comment]
@FilipeLeoni 👆🏼

**Comment by FilipeLeoni** [comment]
@FernandoMiguelS @caiquefonseca , Essa task é bem antiga, passou por várias modificações. Essa era basicamente a coluna da direita do feed de vagas, mas como mudou completamente o design dela, essa task perdeu o sentido

**Comment by caiquefonseca** [comment]
@FernandoMiguelS , depois dá uma olhada se você consegue visualizar essa descrição na US#37, só para não se perder. Checando isso já pode fechar a issue.

**Comment by FernandoMiguelS** [comment]
Irei fechar. Validado.
