### ISSUE TITLE
[Candidato - Candidatura] - Update de Estilo Feed Vagas

### ISSUE THREAD

**Issue by caiquefonseca** [SouJunior/vagas-frontend#189]

**Comment by caiquefonseca** [comment]
@FilipeLeoni , com a criação das outras Tasks, essa deve ser desconsiderada, né?

**Comment by caiquefonseca** [comment]
@FilipeLeoni , considerando o que você me disse no canal do Discord, que essa Tasks deve ser mantida, você poderia fazer aquela descrição completa, como nas outras desta Sprint, para facilitar o entendimento do que deve ser feito?

**Comment by FernandoMiguelS** [comment]
@FilipeLeoni  poderia inserir a descrição para podermos dar inicio aos testes?

**Comment by FilipeLeoni** [comment]
@FernandoMiguelS Essa task é do feed de vagas, foi somente as mudanças de design que posteriormente vieram outras tasks com mais outras mudanças, que já foram validadas nas tasks feed de vagas, então essa é mais uma task que já perdeu o sentido

**Comment by FernandoMiguelS** [comment]
Então iremos fechar. Validado.
