### ISSUE TITLE
[Empresa] Atualizar perfil - Layout

### ISSUE THREAD

**Issue by igords-goncalves** [SouJunior/vagas-frontend#190]
US referente: 
https://github.com/SouJunior/products/issues/68

Figma referente: [Figma](https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX---(-Update-19%2F10%2F2022-)?node-id=89%3A3&t=wn9fqUzX5pFkKGTE-0)

## Descrição

Essa task trata de toda a parte de contrução do layout de acordo com design definido.
 

- [x] Criar sistema de rotas para a página Alterar Perfil
- [x] Reutilizar componente header com menu flutuante 
- [x] Reutilizar componente header com foto do usuário atual
- [x] Criar redirecionamento para página alterar perfil partindo do header ao clicar em "meu pefil" / foto do usuário
- [x] Criação de componente "alterar foto"
- [x] Criação de pop-up de upload da foto
- [x] Criação de botões atualizar e cancelar

## Recursos

API backend: https://vagas-backend.soujunior.tech/api/

______

![image](https://github.com/SouJunior/vagas-frontend/assets/79734585/cd449f4a-e220-40d3-ae13-8e1de372fa81)
![image](https://github.com/SouJunior/vagas-frontend/assets/79734585/713e5469-1d16-4a67-9407-0a14525eb878)
![image](https://github.com/SouJunior/vagas-frontend/assets/79734585/b9a7009f-3e89-41ec-80fa-0dba58a79d8b)
![image](https://github.com/SouJunior/vagas-frontend/assets/79734585/6abfcc93-07b4-4d4b-8475-da1aa6f63f97)
![image](https://github.com/SouJunior/vagas-frontend/assets/79734585/35d73424-7b86-4b6d-a2d8-167e2526ac02)

**Comment by igords-goncalves** [comment]
## Notas de Critérios de Aceite

- Levar em conta os critérios número 1, 2, 3 e 4 que checam e enviam mensagens de erro se o formato e o tamanho da foto são inapropriados
- No critério 5 o que extamente significa: "a foto de perfil será disponibilizada ao clicar em enviar"?

**Comment by igords-goncalves** [comment]
É importante se atentar a reutilização de componets.

**Comment by igords-goncalves** [comment]
Opção de upload perde o style no firefox.



![Image](https://github.com/SouJunior/vagas-frontend/assets/79734585/7b36611f-bb39-45f3-8dd5-ab7504ee8c48)

**Comment by igords-goncalves** [comment]
Adaptação de layout para melhor aproveitamento.


![Image](https://github.com/SouJunior/vagas-frontend/assets/79734585/a54d10e4-ffde-48f9-b39c-931117b562ad)

**Comment by igords-goncalves** [comment]
Observações.

1. O input tipe file não é compatível com outros navegadores além do Edge
![Image](https://github.com/SouJunior/vagas-frontend/assets/79734585/600f0c58-7fed-4072-a4bd-989c497d7bb2)


2. Os estilos em options precisam ser alterados, porém esse recurso é limitado nos browsers uma possível alternativa é utilizar a lib react select.

3. Reveer com o time itens da guia de issues no console
![Image](https://github.com/SouJunior/vagas-frontend/assets/79734585/667c7442-0612-44c6-bb74-6f406beac37c)

**Comment by igords-goncalves** [comment]
Os elementos option de outros sites será um array.

**Comment by JanainaRodrigues07** [comment]
BUG:

- [ ] TE02: Verificar reutilização do componente header com menu flutuante

- [ ] TR01: Testar responsividade da página "Meu perfil" em tela de smart phone na posição vertical
- [ ] TR02: Testar responsividade da página "Meu perfil" em  tela de smart phone na posição horizontal
- [ ] TR03: Testar responsividade da página "Meu perfil" em tela de tablet na posição vertical
- [ ] TR04: Testar responsividade da página "Meu perfil" em tela de tablet na posição horizontal 


Por favor verificar, @igords-goncalves, @Leodias2204, @isabelahyeda

**Comment by JanainaRodrigues07** [comment]
Testes Exploratórios e de Compatibilidade

Descrição: Testes exploratórios feitos nos browsers Google, Microsoft Edge, Mozilla Firefox e Opera

TE01 Verificar redirecionamento para página alterar perfil partindo do header ao clicar em meu pefil  foto do usuário

STATUS: PASSOU

EVIDÊNCIAS:
[Google]


https://github.com/SouJunior/vagas-frontend/assets/110006150/7bbec1b3-c87c-44c7-bcab-b7d707a7ef52


[Microsoft Edge]


https://github.com/SouJunior/vagas-frontend/assets/110006150/8da46676-33e8-47e0-908c-59f28552891b


[Mozilla Firefox]


https://github.com/SouJunior/vagas-frontend/assets/110006150/0c647f8d-f29b-4d1c-8c2a-c63ba66bc1dc


[Opera]


https://github.com/SouJunior/vagas-frontend/assets/110006150/6909c128-24a0-4418-aa74-4aa24895e2ec


_______________________________________________________________________________________________________________________________

TE02 Verificar reutilização do componente header com menu flutuante

STATUS: FALHOU

APONTAMENTO: Existe a reutilização do componente header, porém o menu da página "Meu perfil" não é flutuante

EVIDÊNCIA:
[Google]


https://github.com/SouJunior/vagas-frontend/assets/110006150/b241fe9f-70e1-4ddc-b0c0-6e1445e5f003


[Microsoft Edge]


https://github.com/SouJunior/vagas-frontend/assets/110006150/79ed75cf-ced7-4329-9d95-22b3ecd3e019


[Mozilla Firefox]


https://github.com/SouJunior/vagas-frontend/assets/110006150/3749b7c7-3a04-430f-9a65-88a6297e8600


[Opera]


https://github.com/SouJunior/vagas-frontend/assets/110006150/f66a712c-3cfb-4378-96ea-9976ca90de48


_______________________________________________________________________________________________________________________________

TE03 Verificar reutilização do componente header com foto do usuário atual

STATUS: PASSOU

APONTAMENTO: Header exibe a foto atual do usuário, porém não está sendo possível alterar foto - Bug reportado na task #191

EVIDÊNCIA:
[Google]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/65ab3808-cc02-46ee-9168-4e803ed6bc1c)


[Microsoft Edge]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/3a0ebe8e-855e-4de8-a192-7d80ea08877e)


[Mozilla Firefox]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/826d2f14-4d96-46f6-8f7e-86f5adc5631f)


[Opera]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/47348a37-0e2a-4136-9567-d80983f910d8)


_______________________________________________________________________________________________________________________________

TE04 Verificar a existência do componente alterar foto

STATUS: PASSOU

EVIDÊNCIA:
[Google]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/38ff3373-3004-408b-bee9-5d5c5493ed05)


[Microsoft Edge]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/dc7e17d3-0c0b-4b4d-8e81-d2679fcd48b5)


[Mozilla Firefox]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/3244003a-2970-42ff-9c76-3b28e9c5d66a)


[Opera]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/395ecf1c-9755-4a24-a755-33803a96ebb1)


_______________________________________________________________________________________________________________________________

TE05 Verificar abertura de tela para upload de foto

STATUS: PASSOU

EVIDÊNCIA:
[Google]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/b9359fcb-04e5-444a-8eef-f8971138613b)


[Microsoft Edge]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/97c077fe-b6d5-4166-863f-bb710edbeea4)


[Mozilla Firefox]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/8d72c59d-f67f-4acb-b5a9-ef7fa59d4223)


[Opera]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/0b8b3072-a784-48e0-85b4-6a3810da20ee)


_______________________________________________________________________________________________________________________________

TE06 Verificar a existências dos botões Atualizar e Cancelar

STATUS: PASSOU

EVIDÊNCIA:
[Google]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/b6834844-cc49-46ff-a7bc-b13815c96790)


[Microsoft Edge]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/b66f991d-1254-44f1-9182-6231215d9878)


[Mozilla Firefox]


![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/06efba0d-5473-4547-8f47-4f494fb686d2)


[Opera]



![Image](https://github.com/SouJunior/vagas-frontend/assets/110006150/e56dcf56-ddd3-494f-b680-54c3132aea34)

**Comment by JanainaRodrigues07** [comment]
@igords-goncalves, @isabelahyeda, @Leodias2204 

Teste Responsivo

TR01: Testar responsividade da página "Meu perfil" em tela de smart phone na posição vertical

Descrição: Testes feitos em tela mobile a partir de 357x668 e maiores

STATUS: FALHOU

APONTAMENTO: A página ultrapassa os limites de tela, de modo que o usuário precisa usar scroll para visualizar partes da página 

EVIDÊNCIA:


https://github.com/SouJunior/vagas-frontend/assets/110006150/bd6859ff-5495-496a-9c54-49f67ab897da


______________________________________________________________________________________________________________________________

TR02: Testar responsividade da página "Meu perfil" em tela de smart phone na posição horizontal 

Descrição: Testes feitos em tela mobile a partir de 668x357 e maiores

STATUS: FALHOU

APONTAMENTO: A página ultrapassa os limites de tela, de modo que o usuário precisa usar scroll para visualizar partes da página

EVIDÊNCIA:


https://github.com/SouJunior/vagas-frontend/assets/110006150/6f328130-b084-419d-b4bc-0043ad941bc1


______________________________________________________________________________________________________________________________

TR03: Testar responsividade da página "Meu perfil" em tela de tablet na posição vertical

Descrição: Testes feitos em tela de 768x1024

STATUS: FALHOU

APONTAMENTO: A página ultrapassa os limites de tela, de modo que o usuário precisa usar scroll para visualizar partes da página

EVIDÊNCIA:


https://github.com/SouJunior/vagas-frontend/assets/110006150/311c51ab-52da-41a0-964c-8c404883e713


______________________________________________________________________________________________________________________________

TR04: Testar responsividade da página "Meu perfil" em tela de tablet na posição horizontal 

Descrição: Testes feitos em tela de 1024x768

STATUS: FALHOU

APONTAMENTO: A página ultrapassa os limites de tela, de modo que o usuário precisa usar scroll para visualizar partes da página

EVIDÊNCIA:



https://github.com/SouJunior/vagas-frontend/assets/110006150/0e5e4e80-2136-41fb-96b2-4f473f603ccf

**Comment by igords-goncalves** [comment]
> BUG:
> 
> - [ ] TE02: Verificar reutilização do componente header com menu flutuante
> 
> - [ ] TR01: Testar responsividade da página "Meu perfil" em tela de smart phone na posição vertical
> - [ ] TR02: Testar responsividade da página "Meu perfil" em  tela de smart phone na posição horizontal
> - [ ] TR03: Testar responsividade da página "Meu perfil" em tela de tablet na posição vertical
> - [ ] TR04: Testar responsividade da página "Meu perfil" em tela de tablet na posição horizontal 
> 
> 
> Por favor verificar, @igords-goncalves, @Leodias2204, @isabelahyeda

@JanainaRodrigues07 poderia detalhar melhor por favor o ticket TE02?

**Comment by JanainaRodrigues07** [comment]
Testes Exploratório - TE02: Verificar reutilização do componente header com menu flutuante

DETALHAMENTO: Entende-se por header com menu flutuante o cabeçalho com acesso ao menu que permanece fixo na parte superior da tela ao rolar para baixo. Ao executar o teste "TE02: Verificar reutilização do componente header com menu flutuante", concluiu-se que o header com acesso ao menu (dito que o acesso ao menu se dá ao clicar na foto de perfil) encontra-se na parte superior da tela, no entanto, ao rolar para baixo (como mostra no vídeo de evidência) o header some, ou seja, não acompanha a rolagem da página como deveria ser.

Evidência:


https://github.com/SouJunior/vagas-frontend/assets/110006150/9e2da4f7-ae59-4adf-972e-54c10908b185

@igords-goncalves, essa foi a conclusão do teste baseado no entendimento de menu flutuante que, segundo o que foi descrito nesta tasks, deveria existir um menu flutuante no componente header. Caso tenha algum equívoco da minha parte ou mais alguma dúvida vamos nos falando.

**Comment by igords-goncalves** [comment]
@JanainaRodrigues07 Essa funcionalidade não existe nas demais páginas a não ser na pagina home, o comportamento do Header nas páginas de dashboard está correto.

**Comment by JanainaRodrigues07** [comment]
RETESTES - Testes Responsivos

- TR01: Testar responsividade da página "Meu perfil" em tela de smart phone na posição vertical
- TR02: Testar responsividade da página "Meu perfil" em tela de smart phone na posição horizontal
- TR03: Testar responsividade da página "Meu perfil" em tela de tablet na posição vertical
- TR04: Testar responsividade da página "Meu perfil" em tela de tablet na posição horizontal

STATUS: Todos os testes passaram

________________________________________________________________________________________________________________________________________

Resultado dos retestes

TR01: Testar responsividade da página "Meu perfil" em tela de smart phone na posição vertical

Descrição: Testes feitos em tela mobile a partir de 357x668 e maiores

STATUS: PASSOU

EVIDÊNCIA:



https://github.com/SouJunior/vagas-frontend/assets/110006150/ac9ba6cf-c396-42e8-b6f9-bbfd81a5d952

________________________________________________________________________________________________________________________________________

TR02: Testar responsividade da página "Meu perfil" em tela de smart phone na posição horizontal

Descrição: Testes feitos em tela mobile a partir de 668x357 e maiores

STATUS: PASSOU

EVIDÊNCIA:


https://github.com/SouJunior/vagas-frontend/assets/110006150/5ec14bdd-8f81-48f0-8fb5-8f6da6aaf905

________________________________________________________________________________________________________________________________________

TR03: Testar responsividade da página "Meu perfil" em tela de tablet na posição vertical

Descrição: Testes feitos em tela de 768x1024

STATUS: PASSOU

EVIDÊNCIA:



https://github.com/SouJunior/vagas-frontend/assets/110006150/e6c2886c-ea47-4986-83ac-ee55e53cf8d3

________________________________________________________________________________________________________________________________________

TR04: Testar responsividade da página "Meu perfil" em tela de tablet na posição horizontal

Descrição: Testes feitos em tela de 1024x768

STATUS: PASSOU

EVIDÊNCIA:


https://github.com/SouJunior/vagas-frontend/assets/110006150/30be80e6-9dcc-4fdf-ab6c-df181f26a7ab
