### ISSUE TITLE
[Empresa] Atualizar perfil - Validação de forms/Integraçao

### ISSUE THREAD

**Issue by igords-goncalves** [SouJunior/vagas-frontend#192]
US referente: 
https://github.com/SouJunior/products/issues/68

Figma referente: [Figma](https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX---(-Update-19%2F10%2F2022-)?node-id=89%3A3&t=wn9fqUzX5pFkKGTE-0)

## Descrição
 
Essa task trata toda a parte de validação dos inputs do formulário e seguraça da submissão de dados.

- [x] Capturar inputs do formulário com React Hook forms para validação
~- [ ] Validar formulários com mensagens de erro através do Yup Resolver~
- [x] Validar formulário de Text Area e limitar quantidade de caracteres
~- [ ] O campo CNPJ deve ter a máscara CNPJ assim como em cadastro~
~- [ ] Criar uma função para tratativa de caracteres em CNPJ assim como em cadastro~
- [x] Implementar funcionalidade de logout
~- [ ] garantir que a foto seja submetida com tamanho e proporção correta~
- [x] A foto do usuário deve ser atualizada no header e inserida no componente "alterar foto"
- [x] Bloquear a submissão se existir qualquer tipo de erro no formulário.

## Recursos

API backend: https://vagas-backend.soujunior.tech/api/
Yup Validations: https://github.com/react-hook-form/resolvers#Yup
______

**Comment by igords-goncalves** [comment]
@isabelahyeda teremos que utilizar nova estratégia para setar valores de dados no inputs, pois setando os dados como placeholder não é uma boa prática e qualquer alteração feita nos placeholder será refletida nos dados da requisição.

Abaxio simulei uma alteração de cores nos placeholders dos inputs e o resultado foi esse.


![Image](https://github.com/SouJunior/vagas-frontend/assets/79734585/ec1b33c5-836d-4d18-8afa-c34e0d25388e)

**Comment by igords-goncalves** [comment]
@Jacqueline2021 @Vanessapcs Talvez não faça sentido limitar a foto do usuário pelas proporções como 400 x 400 pois a funcionalidade de recorte já vai colocar na proporção correta, o melhor acredito que seria limitar pelo tamanho.

**Comment by isabelahyeda** [comment]
@igords-goncalves @limaricardo Sim, verdade. Seria melhor ir pelo value do input e não placeholder. O que vocês acham?
