### ISSUE TITLE
Component: LoginCard

### ISSUE THREAD

**Issue by CaaioSB** [SouJunior/vagas-frontend#27]
- [x] Os dados do usuário devem ser preenchidos manualmente;  
- [x] O checkbox "Me mantenha conectado" não é obrigatório;
- [x] Caso selecionado, o sistema irá salvar as credenciais do usuário, não sendo necessário refazer o login
- [x] Quando o usuário clicar no botão Criar Conta, o sistema deve executar US_Cadastro
- [x] Quando o usuário clicar no link "Esqueci minha senha" o sistema deve executar a US_Esqueci_minha_senha
- [x] https://github.com/SouJunior/vagas-frontend/issues/78

**Comment by wouerner** [comment]
@nesantana Por favor, validar a necessidade da criação de componentes.

Até o @nesantana validar, a issue vai ficar aberta como sugestão de melhoria, caso a issue não seja valida vamos fechar novamente.

**Comment by igords-goncalves** [comment]
## Protótipo



![Image](https://user-images.githubusercontent.com/79734585/204795241-27655696-e590-4f82-b340-83e64cb1011e.png)

**Comment by Rica-Jesus** [comment]
Ícone cadeado está em cima do olho de ocultar ou mostrar a senha, qual a posição?

**Comment by igords-goncalves** [comment]
Seguem as imagens do relato acima.

![Image](https://user-images.githubusercontent.com/79734585/205124826-c8e70994-8677-41f9-be14-4f791c4268ab.png)


![Image](https://user-images.githubusercontent.com/79734585/205124982-60af48c4-e3d0-4c02-843d-704012773096.png)

**Comment by igords-goncalves** [comment]
Realizei testes em outros navegadores, e ao que parece somente o Edge da Microsoft que disponibiliza essa opção por padrão.

![Image](https://user-images.githubusercontent.com/79734585/205356662-aa4e97bc-9a98-4df0-b537-eae09fafd20c.png)

**Comment by igords-goncalves** [comment]
@Rica-Jesus faz-se necessário também saber onde ficará o posicionamento do elemento "Esqueci minha senha como no item "Quando o usuário clicar no link "Esqueci minha senha" o sistema deve executar a US_Esqueci_minha_senha".

**Comment by igords-goncalves** [comment]
@Rica-Jesus será necessário verificar algumas coisas em relação a resoluções de tela, pois o layout em algumas resoluções encontra-se quebrado.
![image](https://user-images.githubusercontent.com/79734585/205667303-f663f821-f24b-42c9-9773-4e6d9af40bba.png)

**Comment by igords-goncalves** [comment]
* Quando o usuário clicar no link "Esqueci minha senha" o sistema deve executar a US_Esqueci_minha_senha

@rica @JeanVictorferreira de acordo com o critério acima precisamos saber se essa nova tela será aberta na mesma guia ou em uma nova guia?

**Comment by igords-goncalves** [comment]
> @Rica-Jesus será necessário verificar algumas coisas em relação a resoluções de tela, pois o layout em algumas resoluções encontra-se quebrado. ![image](https://user-images.githubusercontent.com/79734585/205667303-f663f821-f24b-42c9-9773-4e6d9af40bba.png)

Como solução para este problema, em acordo com time @SouJunior/ux e @JeanVictorferreira iremos dimensionar os elementos da tela de login para que os mesmos se encaixem numa resolução ideal e comum a todos os usuários. Todas essas constatações em relação a esse problema com quebra de layout devido a escolha da resolução no protótipo, foram observadas com base em estudos e pesquisa, juntamente com o time de UX/UI parceiros de Squad e Mentoria.

Toda essa alteração deverá assegurar que a ideia do design para tela de login seja mantida e fiel ao que foi pensado e planejado no protótipo

**Comment by igords-goncalves** [comment]
> > @Rica-Jesus será necessário verificar algumas coisas em relação a resoluções de tela, pois o layout em algumas resoluções encontra-se quebrado. ![image](https://user-images.githubusercontent.com/79734585/205667303-f663f821-f24b-42c9-9773-4e6d9af40bba.png)
> 
> Como solução para este problema, em acordo com time @SouJunior/ux e @JeanVictorferreira iremos dimensionar os elementos da tela de login para que os mesmos se encaixem numa resolução ideal e comum a todos os usuários. Todas essas constatações em relação a esse problema com quebra de layout devido a escolha da resolução no protótipo, foram observadas com base em estudos e pesquisa, juntamente com o time de UX/UI parceiros de Squad e Mentoria.
> 
> Toda essa alteração deverá assegurar que a ideia do design para tela de login seja mantida e fiel ao que foi pensado e planejado no protótipo

Após análise decidi optar por deixar o layout fluído em relação a altura mesmo não sendo a opção ideal, por entender que essa quebra de layout se trata de um problema no design, logo assim que/se o protótipo receber uma atualização quando as boas práticas de resoluções e tela de usuário, essas novas mudanças podem ser aplicadas.

**Comment by igords-goncalves** [comment]
Todas as sub-tasks dessa issue estão completas, logo a mesma já pode ser fechada.
