### ISSUE TITLE
Screen: Login

### ISSUE THREAD

**Issue by wouerner** [SouJunior/vagas-frontend#3]
O usuário gostaria de logar no sistema.

Fazer tela de login, com logo do projeto, redirecionando para lista de vagas.

- usuario (numeros e letras)
- senha

Criterio de aceite:

- Redirecionar para lista de vagas.

OBS: usar dados fictícios por enquanto.

- [x] Quando o usuário clicar no botão Saiba Mais, deve ser redirecionado para o Site Sou Júnior; **[COLOCAR LINK DO SITE]**

**Comment by Rhyan-eduardo** [comment]
![Image](https://user-images.githubusercontent.com/67023605/184433432-81e5b218-bd53-4734-b1aa-6d8887c0f6e5.png)

Link do Protótipo da Tela de Login no Figma : 
[Tela de login](https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX?node-id=246%3A1633)

**Comment by Rhyan-eduardo** [comment]
Os assets estão sendo preparados para exportação!

Todos os assets de suas respectivas telas estão neste repositório no drive : 

[Google Drive](https://drive.google.com/drive/folders/1-DmGt1gOwJn4qFsYaGJEa3Flw-4W0z8e?usp=sharing)

( Comunicar a @Rhyan-eduardo a falta de possível asset... )

**Comment by CaaioSB** [comment]
Olá =)

O layout realmente só esta disponível para dispositivos desktop?

Tenho interesse em pegar essa task para tocar.

**Comment by allbertuu** [comment]
@CaaioSB Atualmente só Desktop.

**Comment by CaaioSB** [comment]
Vocês que colocaram o rostinho na issue vão tocar a task? 🤔

**Comment by allbertuu** [comment]
> Vocês que colocaram o rostinho na issue vão tocar a task? 🤔

Gotcha! Exatamente. :)

**Comment by allbertuu** [comment]
### Componentes da aplicação - React
- [ ] Button 
2 variações: filled - outline
- [ ] Input
- [ ] Login Card

**Comment by CaaioSB** [comment]
@allbertuu sugiro que o desenvolvimento dessa interface seja temporariamente pausado para a criação dos componentes em outro PR.

Afins de organizar e melhorar o code review e aperfeiçoar o desenvolvimento precisamos criar uma nova issue para cada um dos componentes que não existem na plataforma hoje.

Assim que todos os componentes necessários estiver desenvolvido podemos prosseguir com o desenvolvimento das interfaces, certamente teremos ganhos nisso.

Por fim, adicionamos nessa issue todas as outras issues que precisam ser resolvidas para dar prosseguimento ao desenvolvimento da interface de login.

[Componente Input #29](https://github.com/SouJunior/linkedin-frontend/issues/29)
[Componente Button #28](https://github.com/SouJunior/linkedin-frontend/issues/28)
[Componente Card #27](https://github.com/SouJunior/linkedin-frontend/issues/27)

**Comment by CaaioSB** [comment]
Infelizmente a @SilviaLTeixeira fechou todas as issues que desanexa a criação do componente da criação de uma interface, selo eXtreme Go Horse.

**Comment by allbertuu** [comment]
> @allbertuu sugiro que o desenvolvimento dessa interface seja temporariamente pausado para a criação dos componentes em outro PR.
> 
> Afins de organizar e melhorar o code review e aperfeiçoar o desenvolvimento precisamos criar uma nova issue para cada um dos componentes que não existem na plataforma hoje.
> 
> Assim que todos os componentes necessários estiver desenvolvido podemos prosseguir com o desenvolvimento das interfaces, certamente teremos ganhos nisso.
> 
> Por fim, adicionamos nessa issue todas as outras issues que precisam ser resolvidas para dar prosseguimento ao desenvolvimento da interface de login.
> 
> [Componente Input #29](https://github.com/SouJunior/linkedin-frontend/issues/29) [Componente Button #28](https://github.com/SouJunior/linkedin-frontend/issues/28) [Componente Card #27](https://github.com/SouJunior/linkedin-frontend/issues/27)

Olá, Caio. Tudo bem? Espero que sim.

Conforme discutido entre a equipe de frontend, optamos por fechar as issues. 
É importante entender que toda ajuda é bem-vinda, mas deve estar de acordo com as regras de contribuição open-source deste projeto. Sugiro dar uma olhada no arquivo `contribuindo.md`, lá no repositório principal do Frontend, e entender suas reais capacidades. Se deseja participar de forma mais ativa, tente ao menos conversar conosco para entender quais as demandas atuais, assim você pode ajudar o projeto de forma mais eficiente, entende?
Reitero que, "criar issues", sem a permissão da equipe, afeta e prejudica o nosso progresso, pois estamos constantemente alinhando e discutindo soluções, e para então criar issues para sanar esses deficits.
Espero que entenda, e que tenha ficado claro que somos uma equipe já formada, e está progredindo com muita calma e carinho por este projeto.

Tenha um excelente dia! ✨

**Comment by CaaioSB** [comment]
O contribuindo.md não tem nenhuma regra de contribuição open source, e antes de criar as issues foi realmente aberta uma thread no Discord onde acabei discutindo o problema de cada um fazer o componente durante o desenvolvimento da interface, conversei isso até mesmo com o @wouerner.

Essa minha contribuição surgiu a partir do momento que eu visualizei outros PR com códigos que poderiam ser componentes e que não são ainda, a replicação de código pode ser alta se não se atentar aos pontos que eu informei, afinal, ta cada um desenvolvendo o "componente" conforme a necessidade da interface e não do projeto.

**Comment by allbertuu** [comment]
Esperando decisão do @SouJunior/ux na escolha da tela para confecção do @SouJunior/frontend: com gradiente, ou sem gradiente.

**Comment by wouerner** [comment]
> Infelizmente a @SilviaLTeixeira fechou todas as issues que desanexa a criação do componente da criação de uma interface, selo eXtreme Go Horse horse.

Acredito que esse comentário não foi pertinente, principalmente em um projeto onde é quase que exclusivamente tocado por pessoas Juniors, com 0 ou pouquíssima experiência.

Não passou nenhum pouco o sentimento de profissionalismo que se esperado de alguém com experiência de mercado.

O time de frontend tem autonomia total para fechar e abrir issues e recusar contribuições que eles entenderem, reabri as issues apenas porque a ideia em si é boa e pedi uma revisão do mentor.

Apesar disso espero um comportamento mais exemplar seu @CaaioSB .

**Comment by CaaioSB** [comment]
> > Infelizmente a @SilviaLTeixeira fechou todas as issues que desanexa a criação do componente da criação de uma interface, selo eXtreme Go Horse horse.
> 
> Acredito que esse comentário não foi pertinente, principalmente em um projeto onde é quase que exclusivamente tocado por pessoas Juniors, com 0 ou pouquíssima experiência.
> 
> Não passou nenhum pouco o sentimento de profissionalismo que se esperado de alguém com experiência de mercado.
> 
> O time de frontend tem autonomia total para fechar e abrir issues e recusar contribuições que eles entenderem, reabri as issues apenas porque a ideia em si é boa e pedi uma revisão do mentor.
> 
> Apesar disso espero um comportamento mais exemplar seu @CaaioSB .

De fato vocês tem autonomia, em momento nenhum discordei, no meu comentário está bem claro que era uma sugestão, uma vez que não aceitou eu apenas disse um fato que ocorre no mundo da programação, que é o "go horse", o go horse foi o meu maior vício quando eu estava aprendendo a programar, prejudica muito.

Quando não se tem experiência é interessante aprender com alguém que sabe ao menos um pouco mais, esse era o papel que eu desejava fazer aqui, afinal, é um repositório open source.

["_Se você tiver algum feedback, por favor nos deixe saber por meio do nosso [Discord](https://discord.gg/naTaHgZZpz). Ou fazendo uma [contribuição](https://github.com/SouJunior/linkedin-frontend#contribui%C3%A7%C3%A3o)._".](https://github.com/SouJunior/linkedin-frontend/blob/main/README.md#feedback)

**Comment by allbertuu** [comment]
No aguardo da resolução da pendência de alguns assets para posterior conclusão desta tela.

**Comment by allbertuu** [comment]
No aguardo da resolução da pendência de alguns assets para posterior conclusão desta tela.

**Comment by allbertuu** [comment]
Já temos os assets da tela.

**Comment by allbertuu** [comment]
Time Frontend está sem o asset do background, azul com detalhes circulares. 
Seria ótimo discutir também se os detalhes circulares serão um asset em formato SVG, para que possamos utilizar diversas vezes no desenvolvimento da tela, devido à esse elemento estar muito presente nas telas.

**Comment by Rica-Jesus** [comment]
@SouJunior/ux conforme nos falamos

**Comment by igords-goncalves** [comment]
Em complemento os assets citados são esses 

![Image](https://user-images.githubusercontent.com/79734585/206300344-64bacabe-767d-4c87-88d2-29dda75c8cc6.png)

**Comment by allbertuu** [comment]
## AVISO ⚠
Essa task será fechada, pois agora as tasks de uma US serão agrupadas em Milestones, e não uma task generalista e dificil de monitorar (como essa).

Resumindo:
NÃO MAIS **uma issue** agrupando várias issues menores.
MAS AGORA **um milestone** agrupando várias issues e pull requests para solucionar o problema maior (geralmente uma US).

O Milestone referente a essa US (Login - M) é: https://github.com/SouJunior/vagas-frontend/milestone/1
