### ISSUE TITLE
Component: Update job card

### ISSUE THREAD

**Issue by allbertuu** [SouJunior/vagas-frontend#39]
Olhar o [Figma ](https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX?node-id=291%3A875) para conferir se a imagem abaixo ainda está atualizada.

![Image](https://user-images.githubusercontent.com/89992304/190286158-3bcffa32-7502-46e1-988f-38748b0d1d8c.png)

**Comment by allbertuu** [comment]
Após reunião com membros da equipe de UI/UX, essa task está parada por conta de várias inconsistências no prótotipo que necessitam revisão da equipe de UI/UX.
- no momento o botão está sem funcionalidade no que tange ao código (update de um JobCard específico)

**Comment by Rica-Jesus** [comment]
@JeanVictorferreira @SouJunior/ux temos algum retorno sobre este block?

**Comment by wouerner** [comment]
nice job

**Comment by igords-goncalves** [comment]
Fechando Issue pois a mesma será contemplada dentro de futuras Sprints
