### ISSUE TITLE
Criar módulos ao invés de paginas soltas e sozinhas

### ISSUE THREAD

**Issue by KarinaMel0** [SouJunior/vagas-frontend#64]
Eu tomei liberdade de dar uma olhada no projeto e percebi que as paginas em sí não possuem uma organização, poderíamos criar pastas com módulos, assim com os  seus respectivos testes e o arquivo de estilo.

**Comment by allbertuu** [comment]
Eu achei muito interessante. Não foi realizado algo ainda nesse sentido.

O que acham?
@nesantana @SilviaLTeixeira @CarlosJunioor @FilipeLeoni @SouJunior/frontend

**Comment by SilviaLTeixeira** [comment]
Acho que sim é uma ideia valida para o futuro mas agora estamos correndo pra entregar a tela de login integrada com o back nao seria o momento . Acredito que depois de entregar essa tela seria sim o momento ideal para isso . Podemos colocar a tua ideia no backlog em um draft para ser feito no futuro o que acham? @SouJunior/frontend

**Comment by allbertuu** [comment]
A ideia já foi passada à toda equipe Frontend, e gostamos muito! 

Irei fechar essa issue por representar uma sugestão que já foi absorvida (e que será implementada no futuro).

Muito obrigado @KarinaMel0 pela colaboração e engajamento à fazer deste projeto, um projeto maravilhoso 💙
