### ISSUE TITLE
Validação de formulários

### ISSUE THREAD

**Issue by allbertuu** [SouJunior/vagas-frontend#78]
A lógica por trás da validação de campos em um formulário. Nesse caso, primeiramente para solucionar a task `LoginCard`.

Recomendado: utilizar uma biblioteca de validação (Yup, Zod etc) e outra para construção de formulários (react hook form, formik etc)

- [x] Quando o usuário clicar no botão Entrar, o email e a senha devem ser validados;  
  - [x] A opção só ficará disponível após preenchimento dos campos acima
- [x] Caso uma das informações inputadas não seja válida, deve aparecer acima do link "Esqueci minha senha" a frase “EMAIL OU SENHA INVÁLIDOS” em vermelho; **[CRIAR OPÇÃO ESQUECI MINHA SENHA]*
- [x] Caso as informações inputadas sejam validadas, sistema deve executar US_Feed_de_Vagas

**Comment by igords-goncalves** [comment]
Perfeito! Agora é só retirar da task login card todos os itens referentes a validação, certo?

**Comment by allbertuu** [comment]
Isso, irei trazer para cá ainda em formato checklist.

**Comment by allbertuu** [comment]
Reunião entre mim, Alberto, e o @RafaelPires2 . Dia 21/12
### Essa task precisa das seguintes informações:
- Esqueci minha senha
  > Será um modal ou uma página? Se uma página, qual o link para essa tela de redefinição de senha?
  > Obs.: Essa feature não consta ainda no protótipo no Figma. Então precisa-se saber como ela se parecerá.
- Validação (regras de negócio)
  > Quais as regras de negócio para que o campo Senha e Email sejam consideradas válidas? Por ex.: Limite de caracteres.
  > Obs.: Essa feature também não consta ainda no protótipo no Figma. Então precisa-se saber como uma mensagem de erro se parecerá. Por ex: um componente alert.

**Comment by Rica-Jesus** [comment]
Qual será a action ao esquecer a senha? @JeanVictorferreira @LuandaClara

**Comment by LuandaClara** [comment]
Telas feitas e disponíveis no Figma:

https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX---(-Update-19%2F10%2F2022-)?node-id=0%3A1&t=pSbMPrdZeN0gZil8-0

**Comment by igords-goncalves** [comment]
Fechando Issue pois a mesma se encontra dentro da Sprint n° 1
