### ISSUE TITLE
Asset faltante da tela de login

### ISSUE THREAD

**Issue by allbertuu** [SouJunior/vagas-frontend#80]
TASK RETIRADA DA [SCREEN LOGIN](https://github.com/SouJunior/vagas-frontend/issues/3) (fechada)

## Motivo
Em razão da migração de issues generalistas para Milestones, essa foi a pendência que restou da US Login. 

### Sobre
Essa issue serve para resolver essa pendência do asset que são figuras circulares na tela de login.

O asset citado é esse:

![Image](https://user-images.githubusercontent.com/79734585/206300344-64bacabe-767d-4c87-88d2-29dda75c8cc6.png)

_Originally posted by @igords-goncalves in https://github.com/SouJunior/vagas-frontend/issues/3#issuecomment-1341620983_

**Comment by JeanVictorferreira** [comment]
Pessoal, já estou trabalhando para resolver esse asset, ok? Vou informando vocês.

**Comment by Rica-Jesus** [comment]
@JeanVictorferreira não mencionei mas precisamos do arquivo tudo bem?

**Comment by igords-goncalves** [comment]
https://cdn.discordapp.com/attachments/1039135266809581587/1055556903985479805/Circles_details.zip segue o link de download com os assets.
