### ISSUE TITLE
Password and e-mail validation

### ISSUE THREAD

**Issue by Rica-Jesus** [SouJunior/vagas-frontend#89]

**Comment by igords-goncalves** [comment]
Produto não definiu nos critérios: Caso o usuário continue tentando realizar a validação de forma incorreta (isso também é um caso a se pensar para a tela de Login #84) bloquearemos o formulário, como sugerem as especificações no MDN?

https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation


![MDN print](https://user-images.githubusercontent.com/79734585/217826589-8609fc6e-8eec-4a43-9f22-63608938cdbc.png)

**Comment by igords-goncalves** [comment]
Prezados o PR de nº #93 ainda continua em aberto, só será possível realizar a validação do formulário após o merge do mesmo, pois a rota ainda não existe na branch atual.


![Image](https://user-images.githubusercontent.com/79734585/218262753-75ac5313-886f-469b-8e7e-f286b9aa4532.png)

**Comment by igords-goncalves** [comment]
Fechando Issue pois a mesma se encontra dentro da Sprint n° 1
